apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gmt10
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmt10
      release: "1"
  template:
    metadata:
      labels:
        app: gmt10
        release: "1"
    spec:
      containers:
        - name: gmt10
          image: "jerrymannel/gomongotest:1.10"
          env:
            - name: URL
              value: "mongodb://localhost:27017"
          resources:
            requests:
              memory: "50M"
              cpu: "100m"
            limits:
              memory: "75M"
              cpu: "150m"
